version: "3.8"

services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "3000:3000" # Map port 3000 on the host to port 3000 in the container
      environment:
        - MONGO_URI=mongodb://CloudCourse:12345678@mongo:27017
      depends_on:
        - mongo # Ensure MongoDB starts before the app
      networks:
        - app-network

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB's default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: CloudCourse
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
    networks:
      - app-network

volumes:
  mongo-data: # Named volume for MongoDB data

networks:
  app-network: # Shared network for communication
