# swagger.yaml
openapi: 3.0.0
info:
  title: Cloud Course API
  version: 1.0.0
  description: An API for Applied Computing Innovative solution project
servers:
  - url: http://localhost:3000
paths:
  /auth/signup:
    post:
      summary: Signing up the user
      description: Adds a user to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
                - password
                - confirmedPassword
                - email
                - mobile
              properties:
                userName:
                  type: string
                password:
                  type: string
                confirmedPassword:
                  type: string
                email:
                  type: string
                mobile:
                  type: string
                agreedToTermAndCondition:
                  type: boolean
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  success:
                    type: boolean
        "400":
          description: Invalid input
        "409":
          description: User or password is incorrect
  /auth/login:
    post:
      summary: Login the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                userName:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User login successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  jwt:
                    type: string
                  success:
                    type: boolean
        "400":
          description: Invalid input
        "409":
          description: User or password is incorrect
